# Generated by Django 5.0.3 on 2024-04-06 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_string', models.CharField(max_length=120)),
                ('platform', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LocationSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('local_search', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_link', models.CharField(max_length=350)),
                ('job_title', models.CharField(max_length=120)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('company', models.CharField(max_length=100)),
                ('company_location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('apply_type', models.CharField(max_length=35)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('job_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.jobsearch')),
                ('search_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.locationsearch')),
            ],
        ),
    ]
