# Generated by Django 5.0.3 on 2024-04-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearch',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='locationsearch',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
