# Generated by Django 4.2.11 on 2024-04-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0002_jobsearch_active_locationsearch_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='jkey',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='platform',
            field=models.CharField(default='Indeed', max_length=50),
        ),
    ]
